# Generated by Django 5.2 on 2025-11-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='secret_key',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
