# Generated by Django 5.2 on 2025-10-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='secret_key',
            field=models.CharField(default='vendora-868be22d-9f5e-44d6-ab72-ee75f661deb0'),
        ),
    ]
