# Generated by Django 5.2 on 2025-10-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_emailverification_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='secret_key',
            field=models.CharField(default='vendora-481d3844-fa7d-4809-87b3-b1afc9c256cf'),
        ),
    ]
