# Generated by Django 5.2 on 2025-10-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_emailverification_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='secret_key',
            field=models.CharField(default='vendora-6d5f20a1-3dbe-4d42-8ae3-3359d98e9470'),
        ),
    ]
