# Generated by Django 5.2 on 2025-10-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('checked_out', 'checked_out')], default='active', max_length=20),
        ),
    ]
