# Generated by Django 5.2 on 2025-10-02 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_cart_customer'),
        ('products', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartposition',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
