# Generated by Django 5.2 on 2025-11-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_gateway',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
