# Generated by Django 5.2 on 2025-10-28 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_cartposition_product'),
        ('products', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartposition',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddConstraint(
            model_name='cartposition',
            constraint=models.UniqueConstraint(fields=('cart', 'product'), name='unique_product_per_cart'),
        ),
    ]
